fix

diff --git a/firewall/add-default-route b/firewall/add-default-route
--- a/firewall/add-default-route
+++ b/firewall/add-default-route
@@ -28,25 +28,36 @@ ip route replace default via {{ private_net_ip }} dev $(route -n | grep {{ priva
 echo "DNS=8.8.8.8 8.8.4.4" >> /etc/systemd/resolved.conf
 systemctl restart systemd-resolved
 
+# Update DNS and restart systemd-resolved
+echo "DNS=8.8.8.8 8.8.4.4" >> /etc/systemd/resolved.conf
+systemctl restart systemd-resolved
+
 while true
 do
-    ping -c3 -q 8.8.8.8
+    ping -c3 8.8.8.8
     if [ "$?" -eq 1 ]; then
+	echo "ping towrds 8.8.8.8 has failed"
+        echo "ip addr add $default_gateway_interface_ip dev $default_gateway_interface"
         ip addr add $default_gateway_interface_ip dev $default_gateway_interface
-        ip route replace default via $default_gateway_ip dev $defaultgateway_interface
-	
-	#ip addr add 10.0.48.56/24 dev ens18
-	#ip route replace default via 10.0.48.1 dev ens18
-	#ip route del default via 192.168.200.2 dev $(route -n | grep 192.168.200.0 | awk '{print $8}')
-        echo "Firewall has failed. Restoring network"
+        echo "ip route replace default via $default_gateway_ip dev $default_gateway_interface"
+        ip route replace default via $default_gateway_ip dev $default_gateway_interface
+
+        #ip addr add 10.0.48.56/24 dev ens18
+        #ip route replace default via 10.0.48.1 dev ens18
+        echo " ip route del default via 192.168.199.2 dev $(route -n | grep 192.168.199.0 | awk '{print $8}')"
+        ip route del default via 192.168.199.2 dev $(route -n | grep 192.168.199.0 | awk '{print $8}')
+        echo "Firewall has failed. etrexa ta command gia na ginei restore to network"
     fi
 
-    ping -I $(route -n | grep {{ private_net_net_0 }} | awk '{print $8}') -c3 8.8.8.8
-    if [ "$?" -eq 1 ]; then
-	ip route replace default via {{ private_net_ip }} dev $(route -n | grep {{ private_net_net_0 }} | awk '{print $8}')
-	ip addr del {{ default_gateway_interface_ip }} dev {{ parent_interface }}
-	echo "Connection via firewall has been restored"
-    fi 
+    #ping -I $(route -n | grep 192.168.199.0 | awk '{print $8}') -c3 8.8.8.8
+    docker exec firewall ping -c3 8.8.8.8
+    if [ "$?" -eq 0 ]; then
+        echo "ip route replace default via 192.168.199.2 dev $(route -n | grep 192.168.199.0 | awk '{print $8}')"
+        ip route replace default via 192.168.199.2 dev $(route -n | grep 192.168.199.0 | awk '{print $8}')
+        echo "ip addr del  $default_gateway_interface_ip dev ens18"
+        ip addr del  $default_gateway_interface_ip dev ens18
+        echo "Connection via firewall has been restored"
+    fi
 
     # Wait 30 seconds before retrying
     sleep 30
